#FosUserBundle Routes
fos_user_security:
    resource: "@UserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@UserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@UserBundle/Resources/config/routing/registration.xml"
    prefix: /

fos_user_resetting:
    resource: "@UserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@UserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

#HWIOAuthBundle routes
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

facebook_login:
    pattern: /login/check-facebook

google_login:
    pattern: /login/check-google

linkedin_login:
    pattern: /login/check-linkedin
