## HWI OAuthBundle routes, Must Be First Import
hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /service/login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /service/login

linkedin_login:
    path: /service/login/check-linkedin

## FOS UserBundle Routes
fos_user_security:
    resource: "@UserBundle/Resources/config/routing/security.yml"

fos_user_profile:
    resource: "@UserBundle/Resources/config/routing/profile.yml"
    prefix:   /profile

fos_user_register:
    resource: "@UserBundle/Resources/config/routing/registration.yml"
    prefix:   /

fos_user_resetting:
    resource: "@UserBundle/Resources/config/routing/resetting.yml"
    prefix:   /resetting

fos_user_change_password:
    path:            /profile/change-password
    methods:         GET|POST
    defaults:
        _controller: FOSUserBundle:ChangePassword:changePassword

## AJAX Action
user_switch_notification:
    path:            /user/notification/switch
    defaults:
        _controller: UserBundle:Action:switchNotification

# Payment
user_pay:
    path:            /user/pay
    defaults:
        _controller: UserBundle:Payment:Stripe
