services:
#    user.example:
#        class: UserBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
services:
    acme.twig.acme_extension:
        class: UserBundle\Twig\CountryExtension
        tags:
            - { name: twig.extension }

    acme_user.password_resetting:
        class: UserBundle\EventListener\PasswordResettingListener
        arguments: [ @router ]
        tags:
            - { name: kernel.event_subscriber }