imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@MissionBundle/Resources/config/services.yml" }
    - { resource: "@UserBundle/Resources/config/services.yml" }
    - { resource: "@HomePageBundle/Resources/config/services.yml" }
    - { resource: "@TeamBundle/Resources/config/services.yml" }
    - { resource: "@DashboardBundle/Resources/config/services.yml" }
    - { resource: "@CompanyBundle/Resources/config/services.yml" }
    - { resource: "@CalendarBundle/Resources/config/services.yml" }
    - { resource: "@NotificationBundle/Resources/config/services.yml" }
    - { resource: "@InboxBundle/Resources/config/services.yml" }
    - { resource: "@BlogBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
#    host:      "%mailer_host%" # uncomment if you wanna use something else than google
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# FOS UserBundle Configuration
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: UserBundle\Entity\User
    registration:
        form:
            type: UserBundle\Form\RegistrationType
        confirmation:
            from_email:
                address:        server@mail.com # put a valid mail address
                sender_name:    Confimation link
            enabled: false # pass to true to enable sending mail inscriptions
            template:   FOSUserBundle:Registration:email.txt.twig
    profile:
        form:
            type: UserBundle\Form\ProfileFormType
    resetting:
        email:
            template:   UserBundle:Reset:password_resetting.email.twig
            from_email:
                address:        server@mail.com # put a valid mail address
                sender_name:    Reset link
    from_email:
        address:        server@mail.com # put a valid mail address
        sender_name:    Activation link

# Assetic Configuration
assetic:
    assets:
        chosen_css:
            inputs:
              - '@MissionBundle/Resources/public/css/chosen.css'
        chosen_jquery_js:
            inputs:
              - '@MissionBundle/Resources/public/js/jquery-1.6.4.js'
        chosen_jquery_tag_js:
            inputs:
              - '@MissionBundle/Resources/public/js/chosen.jquery.tag.js'
        chosen_config_tag_js:
            inputs:
              - '@MissionBundle/Resources/public/js/chosen.config.tag.js'
        chosen_prism_js:
            inputs:
              - '@MissionBundle/Resources/public/js/prism.js'
        calendar_jquery_ui_css:
            inputs:
              - '@CalendarBundle/Resources/public/css/jquery-ui.css'
        calendar_full_css:
            inputs:
              - '@CalendarBundle/Resources/public/css/fullcalendar.css'
        calendar_css:
            inputs:
              - '@CalendarBundle/Resources/public/css/calendar.css'
        calendar_settings_js:
            inputs:
              - '@CalendarBundle/Resources/public/js/calendar-settings.js'
        calendar_jquery_js:
            inputs:
              - '@CalendarBundle/Resources/public/js/jquery-1.11.3.js'
        calendar_moment_js:
            inputs:
              - '@CalendarBundle/Resources/public/js/moment.js'
        calendar_full_js:
            inputs:
              - '@CalendarBundle/Resources/public/js/fullcalendar.js'
    debug:          "%kernel.debug%"
    use_controller: true
    bundles:        [ToolsBundle, MissionBundle, CalendarBundle, CompanyBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~

hwi_oauth:
    #custom user provider, created from FOSUBUserProvider - will manage the
    #automatic user registration on your site, with data from the provider (facebook. google, etc.)
    #and also, the connecting part (get the token and the user_id)
    connect:
        account_connector: my_user_provider
    # name of the firewall in which this bundle is active, this setting MUST be set
    firewall_names: [main]
    fosub:
        username_iterations: 30
        properties:
            # these properties will be used/redefined later in the custom FOSUBUserProvider service.
            linkedin: linkedin_id
            facebook: facebook_id
            google: google_id
    resource_owners:
        linkedin:
            type:                linkedin
            client_id:           "%linkedin_id%"
            client_secret:       "%linkedin_secret%"
            scope:               "%linkedin_scope%"
        facebook:
            type:                facebook
            client_id:           "%facebook_id%"
            client_secret:       "%facebook_secret%"
            scope:               "%facebook_scope%"
        google:
            type:                google
            client_id:           "%google_id%"
            client_secret:       "%google_secret%"
            scope:               "%google_scope%"
# here you will add one (or more) configurations for resource owners
fos_js_routing:
    routes_to_expose: [fullcalendar_loader, calendar_booking_get, calendar_booking_add, calendar_booking_remove, calendar_booking_edit]

# FOS MessageBundle Multi User Conf
fos_message:
    db_driver:              orm
    thread_class:           InboxBundle\Entity\Thread
    message_class:          InboxBundle\Entity\Message
    new_thread_form:
        type:               FOS\MessageBundle\FormType\NewThreadMultipleMessageFormType
        handler:            fos_message.new_thread_multiple_form.handler
        model:              FOS\MessageBundle\FormModel\NewThreadMultipleMessage
        name:               message
