easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin
    
bundles:
    resource: "./routing_v1.yml"
    prefix: /{_locale}
    requirements:
        _local: "%app_locales%"

home_page:
    path:      /
    defaults:
        _controller: HomePageBundle:Default:expert