## HWI OAuthBundle routes, Must Be First Import
hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /service/login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /service/login

# BackLog
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /wamow-manager

# BackLog
easy_admin_bundle_master:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /master-manager

## Local import
bundles:
    resource: "./routing_v1.yml"
    prefix: /{_locale}
    requirements:
        _locale: "%app_locales%"

home_page:
    path:      /
    defaults:
        _controller: HomePageBundle:Default:noLocal
