team:
    resource: "@TeamBundle/Resources/config/routing.yml"
    prefix:   /

company:
    resource: "@CompanyBundle/Resources/config/routing.yml"
    prefix: /

home_page:
    resource: "@HomePageBundle/Resources/config/routing.yml"
    prefix: /

mission:
    resource: "@MissionBundle/Resources/config/routing.yml"
    prefix: /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix: /

dashboard:
    resource: "@DashboardBundle/Resources/config/routing.yml"
    prefix:   /
