## Must Be First Import !!
user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix: /

calendar:
    resource: "@CalendarBundle/Resources/config/routing.yml"
    prefix:   /

team:
    resource: "@TeamBundle/Resources/config/routing.yml"
    prefix:   /

company:
    resource: "@CompanyBundle/Resources/config/routing.yml"
    prefix: /

home_page:
    resource: "@HomePageBundle/Resources/config/routing.yml"
    prefix: /

mission:
    resource: "@MissionBundle/Resources/config/routing.yml"
    prefix: /

dashboard:
    resource: "@DashboardBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

adesigns_calendar:
    resource: "@ADesignsCalendarBundle/Resources/config/routing.xml"

notification:
    resource: "@NotificationBundle/Resources/config/routing.yml"
    prefix:   /

tools:
    resource: "@ToolsBundle/Resources/config/routing.yml"
    prefix: /

inbox:
    resource: "@InboxBundle/Resources/config/routing.yml"
    prefix:   /inbox

## Must Be Last Import !!!!
blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /
