home_page:
    resource: "@HomePageBundle/Resources/config/routing.yml"
    prefix: /

mission:
    resource: "@MissionBundle/Resources/config/routing.yml"
    prefix: /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix: /

compagny:
    resource: "@CompagnyBundle/Resources/config/routing.yml"
    prefix: /
