## Local import
bundles:
    resource: "./routing_v1.yml"
    prefix: /{_locale}
    requirements:
        _local: "%app_locales%"

home_page:
    path:      /
    defaults:
        _controller: HomePageBundle:Default:expert

## HWI OAuthBundle routes, Must Be First Import
hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /service/login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /service/login
