security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:
            - ROLE_ADVISOR
            - ROLE_CONTRACTOR
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_ADVISOR
            - ROLE_CONTRACTOR
            - ROLE_ALLOWED_TO_SWITCH

    providers:
        in_memory:
            memory:
                users:
                    manager:
                        password: "Q#457SFGR@FHI'wrt;swreye"
                        roles: 'ROLE_SUPER_ADMIN'
                    masterMind:
                        password: "qeHCRTh%#^ghszdg0834534e"
                        roles: 'ROLE_SUPER_ADMIN'

        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern: ^/wamow-manager
            http_basic: ~

        main:
            pattern:                  ^/
            form_login:
                provider:             fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path:           fos_user_security_login
                check_path:           fos_user_security_check
                check_path:           fos_user_security_login
            logout:
                path:                  fos_user_security_logout
                target:                home_page

            oauth:
                resource_owners:
                    linkedin:          /service/login/check-linkedin
                login_path:            /service/login
                failure_path:          /service/login

                oauth_user_provider:
                    service:           my_user_provider
            logout:                    true
            anonymous:                 true

        login:
            pattern:  ^/login$
            security: false

            remember_me:
                secret: "%secret%"
                lifetime: 3000
                path: /
                domain: ~ # Defaults to the current domain from $_SERVER

    access_control:
        - { path: ^/wamow-manager, roles: "ROLE_SUPER_ADMIN" }