security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:
            - ROLE_ADVISOR
            - ROLE_CONTRACTOR
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_ADVISOR
            - ROLE_CONTRACTOR
            - ROLE_ALLOWED_TO_SWITCH

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:                  ^/
            form_login:
                provider:             fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path:           /dashboard
                check_path:           /login_check
                failure_path:         /login

            oauth:
                resource_owners:
                    linkedin:          /service/login/check-linkedin
                login_path:            /service/login
                failure_path:          /service/login

                oauth_user_provider:
                    service:           my_user_provider
            logout:                    true
            anonymous:                 true

        login:
            pattern:  ^/login$
            security: false

            remember_me:
                secret: "%secret%"
                lifetime: 3000
                path: /
                domain: ~ # Defaults to the current domain from $_SERVER
