parameters:
    my_user_provider.class: UserBundle\Security\Core\User\FOSUBUserProvider

services:
    my_user_provider:
        class: "%my_user_provider.class%"
        arguments: ['@fos_user.user_manager', {linkedin: linkedin_id}, '@service_container']

    mission:
        class: MissionBundle\Service\Mission
        arguments: ['@doctrine.orm.entity_manager']

    config.mission:
        class: ToolsBundle\Service\ConfigMission
        arguments: ['@doctrine.orm.entity_manager']

    notification:
        class:     NotificationBundle\Event\NewNotification
        arguments: ['@doctrine.orm.entity_manager']

    app.twig.extension.date:
        class:        Twig_Extensions_Extension_Date
        arguments:
             - "@translator.default"
        tags:
             - { name: 'twig.extension' }

    signed_up:
        class: UserBundle\Services\SignedUp
        arguments: ['@doctrine.orm.entity_manager']

    scoring:
        class: MissionBundle\Service\Scoring
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%scoring_rules%'
            - '%scoring_weight.business_practice%'
            - '%scoring_weight.professional_expertise%'
            - '%scoring_weight.company_size%'
            - '%scoring_weight.mission_kind%'
            - '%scoring_weight.location%'
            - '%scoring_weight.certification%'
            - '%scoring_weight.work_experience%'
            - '%scoring_match_min%'

    wamow.mailer:
        class: ToolsBundle\Service\WamowMailerService
        arguments: ['@mailer', '@translator', '@service_container']

    app.user_mission_listener:
        class: MissionBundle\Listener\UserMissionListener
        arguments: [ '@wamow.mailer', '@translator' ]
        tags:
            - { name: doctrine.event_listener, event: preUpdate, method: preUpdate, entity_manager: default  }

    app.mission_listener:
        class: MissionBundle\Listener\MissionListener
        arguments: ['@scoring']
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    fos_user.listener.flash:
        class: UserBundle\EventListener\FlashListener
        arguments: ['@session', '@translator']