parameters:
    my_user_provider.class: UserBundle\Security\Core\User\FOSUBUserProvider

services:
    my_user_provider:
        class: "%my_user_provider.class%"
        arguments: ['@fos_user.user_manager', {linkedin: linkedin_id}, '@service_container']

    mission:
        class: MissionBundle\Service\Mission
        arguments: ['@doctrine.orm.entity_manager']

    config.mission:
        class: ToolsBundle\Service\ConfigMission
        arguments: ['@doctrine.orm.entity_manager']

    notification:
        class:     NotificationBundle\Event\NewNotification
        arguments: ['@doctrine.orm.entity_manager']

    app.twig.extension.date:
        class:        Twig_Extensions_Extension_Date
        arguments:
             - "@translator.default"
        tags:
             - { name: 'twig.extension' }

    tools.locale_listener:
        class: ToolsBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }

    signed_up:
        class: UserBundle\Services\SignedUp
        arguments: ['@doctrine.orm.entity_manager']

    mission_matching:
        class: MissionBundle\Service\MissionMatching
        arguments: ['@service_container', '@doctrine.orm.entity_manager']

    scoring:
        class: MissionBundle\Service\Scoring
        arguments: ['@doctrine.orm.entity_manager', '%scoring_weight.business_practice%', '%scoring_weight.professional_expertise%', '%scoring_weight.company_size%', '%scoring_weight.mission_kind%', '%scoring_weight.location%']
