parameters:
    my_user_provider.class: UserBundle\Security\Core\User\FOSUBUserProvider

services:
    my_user_provider:
        class: "%my_user_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: ['@fos_user.user_manager',{linkedin: linkedin_id, facebook: facebook_id, google: google_id}]

    mission:
        class: MissionBundle\Service\Mission
        arguments: ['@doctrine.orm.entity_manager']

    team:
        class: TeamBundle\Service\Team
        arguments: ['@doctrine.orm.entity_manager']

    config.mission:
        class: ToolsBundle\Service\ConfigMission
        arguments: ['@doctrine.orm.entity_manager']

    notification:
        class:     NotificationBundle\Event\NewNotification
        arguments: ['@doctrine.orm.entity_manager']

    app.twig.extension.date:
        class:        Twig_Extensions_Extension_Date
        arguments:
             - "@translator.default"
        tags:
             - { name: 'twig.extension' }
