version: '2'

services:
    db:
        image: mysql
        ports:
            - 3306:3306
        volumes:
            - "./.data/db:/var/lib/mysql:rw"
            - "./script:/stack:rw"
        environment:
            MYSQL_ROOT_PASSWORD: root
        command:
            - "/stack/localdb-run.sh"
    php:
        build: php7-fpm
        ports:
            - 9000:9000
        links:
            - db:mysqldb
        volumes:
            - ./symfony:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/app/logs
    nginx:
        build: nginx
        ports:
            - 80:80
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
    elk:
        image: willdurand/elk
        ports:
            - 81:80
        volumes:
            - ./elk/logstash:/etc/logstash
            - ./elk/logstash/patterns:/opt/logstash/patterns
        volumes_from:
            - php
            - nginx
    phpmyadmin:
        image: corbinu/docker-phpmyadmin
        ports:
            - "8080:80"
        environment:
            - MYSQL_USERNAME=root
            - MYSQL_PASSWORD=root
        links:
            - db:mysql
