<?php

namespace NotificationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends EntityRepository
{
    public function getMyNotifications($user, $limit = 10, $offset = 0)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('n')
        ->from('NotificationBundle:Notification', 'n')
        ->where('n.user = :userID')
            ->setParameter('userID', $user)
        ->andWhere('n.status > 0')
        ->orderBy('n.creationDate', 'DESC')
        ->setMaxResults($limit)
        ->setFirstResult($offset);
        return $qb->getQuery()->getResult();
    }
}
