<?php

namespace MissionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BusinessPracticeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessPracticeRepository extends EntityRepository
{
}
