<?php

namespace MissionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * companySizeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class companySizeRepository extends EntityRepository
{
}
