<?php

namespace MissionBundle\Repository;

/**
 * ExperienceShapingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExperienceShapingRepository extends \Doctrine\ORM\EntityRepository
{
}
