<?php

namespace MissionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MissionRepository extends EntityRepository
{
    public function missionsAvailables()
        {
            $qb = $this->_em->createQueryBuilder();
            $qb->select('m')
            ->from('MissionBundle:Mission', 'm')
            ->where('m.applicationEnding > :today')
                ->setParameter('today', new \Datetime())
            ->orderBy('m.applicationEnding', 'DESC');
            return $qb->getQuery()->getResult();
        }
}
