<?php

namespace MissionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProfessionalExpertiseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfessionalExpertiseRepository extends EntityRepository
{
}
