<?php

namespace MissionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StepRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StepRepository extends EntityRepository
{
    // Query get step by mission and position
    public function getStepByMissionAndPosition($missionId, $position = NULL)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('s')
            ->from('MissionBundle:Step', 's')
            ->leftjoin('s.mission', 'm')
            ->where('m.id = :missionId')
                ->setParameter('missionId', $missionId);
        if ($position == NULL) {
            $qb->andWhere('s.status = 1');
        } else {
            $qb->andWhere('s.position = :position')
                ->setParameter('position', $position);
        }
        return $qb->getQuery()->getResult()[0];
    }
}
