<?php

namespace MissionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserMissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserMissionRepository extends EntityRepository
{

    /**
     * @param $user
     * @param $mission
     *
     * @return array
     */
    public function findByUserAndMission($user, $mission)
    {
        $qb = $this->_em->createQueryBuilder();

        $qb
            ->select('um')
            ->from('MissionBundle:UserMission', 'um')
            ->leftJoin('um.mission', 'm')
            ->leftJoin('um.user',  'u')
            ->where('u = :user')
            ->setParameter('user', $user)
            ->andWhere('m = :mission')
            ->setParameter('mission', $mission)
        ;

        return $qb->getQuery()->getResult();
    }

}
