<?php

namespace ToolsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigRepository extends EntityRepository
{
    /**
     * Return the last config entity entred in dB
     *
     * @return \ToolsBundle\Entity\Config
     */
    public function findOneConfig()
    {
        $qb = $this->_em->createQueryBuilder();
        $qb
            ->select('c')
            ->from('ToolsBundle:Config', 'c')
            ->orderBy('c.id', 'ASC')
            ->setMaxResults(1)
        ;
        return $qb->getQuery()->getResult()[0];
    }
}
