<?php

namespace ToolsBundle\Repository;

/**
 * PreregisterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PreregisterRepository extends \Doctrine\ORM\EntityRepository
{
}
