<?php

namespace ToolsBundle\Repository;

use Doctrine\ORM\EntityRepository;

use Symfony\Component\Validator\Constraints\DateTime;

/**
 * ProfilePictureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfilePictureRepository extends EntityRepository
{

    public function getLastProfilePictureByUser($user)
    {
        $profilePicture = array();
        $profilePicture = $this->findByUser($user);

        usort($profilePicture, function($a, $b) {
            $ad = $a->getUploadDate();
            $bd = $b->getUploadDate();

            if ($ad == $bd)
                return 0;

            return $ad > $b ? -1 : 1;
        });

        return (empty($profilePicture)) ? null : $profilePicture[0];
    }

}
