<?php

namespace ToolsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReadResumeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReadResumeRepository extends EntityRepository
{
}
