newsletter_list:
    path:      /newsletter
    defaults:
        _controller: BlogBundle:NewsLetter:list

newsletter_show:
    path:      /newsletter/{id}
    defaults:
        _controller: BlogBundle:NewsLetter:show

## Must Be Last Import !!!
article_view:
    path:      /{url}
    defaults:
        _controller: BlogBundle:Article:view