<?php

namespace CompagnyBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CompagnyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompagnyRepository extends EntityRepository
{
}
