easy_admin:
    entities:
        Certification:
            class: MissionBundle\Entity\Certification
            label: 'Certification'
            list:
                title: "Certifications"
                fields: 
                    - 'id'
                    - 'name'
            form:
                fields:
                    - { property: 'name', type: 'text' }
