easy_admin:
    entities:
        Inspector:
            class: CompanyBundle\Entity\Inspector
            label: 'Inspector'
            list:
                title: "Inspectors"
                fields: 
                    - 'id'
                    - 'name'
            form:
                fields:
                    - { property: 'name', type: 'text' }
