easy_admin:
    entities:
        Mission:
            class: MissionBundle\Entity\Mission
            label: 'Mission'
            list:
                title: "Missions"
                fields: 
                    - 'id'
                    - 'title'
                    - 'resume'
                    - { property: 'creationDate', type: 'date' }
                    - 'statusTrans'
                    - 'nbOngoing'
#                    - 'originalPrice'
#                    - 'originalBudget'
#                    - 'applicationDEadline'
                    - { property : 'getScoreDetailsAsString' }
            form:
                fields:
                    - { property: 'resume', type: 'textarea' }
                    - { property: 'nbOngoing', type: 'number' }
                    - { property: 'nextUpdateScoring'}
                    - { property: 'scoreDetailsAsString' }
                    - { property: 'originalPrice'}
                    - { property: 'originalBudget' }
                    - { property: 'price'}
                    - { property: 'budget' }
                    - { property: 'applicationEnding' }
                    - { property: 'missionBeginning' }
                    - { property: 'missionEnding' }
