easy_admin:
    entities:
        Preregister:
            class: ToolsBundle\Entity\Preregister
            label: 'Pregister'
            list:
                title: "Pregisters"
                fields: 
                    - 'id'
                    - 'email'
                    - 'firstname'
                    - 'lastname'
            form:
                fields:
                    - { property: 'email', type: 'email' }
                    - { property: 'firstname', type: 'text' }
                    - { property: 'lastname', type: 'text' }
                    - { property: 'company', type: 'text' }
                    - { property: 'country', type: 'country' }
                    - { property: 'comment', type: 'textarea' }
