easy_admin:
    entities:
        UserMission:
            class: MissionBundle\Entity\UserMission
            label: 'UserMission'
            list:
                actions:
                    - { name: 'show', icon: 'search' }
                title: "UserMissions"
                fields:
                    - 'id'
                    - 'user'
                    - 'mission'
                    - 'statusTrans'
                    - 'score'
                    - 'updateDate'
            show:
                fields:
                    - { property : 'user' }
                    - { property : 'mission' }
                    - { property : 'statusTrans' }
                    - { property : 'creationDate' }
                    - { property : 'updateDate' }
                    - { property : 'interestedAt' }
                    - { property : 'getScoreDetailsAsString' }
            disabled_actions: ['delete', 'new', 'edit']

