easy_admin:
    entities:
        User:
            class: UserBundle\Entity\User
            label: 'User'
            list:
                title: "Users"
                fields:
                    - 'id'
                    - 'firstname'
                    - 'lastname'
                    - 'email'
                    - 'roles'
                    - 'company'
                    - 'enabled'
                    - 'userAgreement'
            form:
                fields:
                    - { property: 'firstname', type: 'text' }
                    - { property: 'lastname', type: 'text' }
                    - { property: 'email', type: 'email' }
                    - { property: 'status', type: 'choice', type_options: { required: true, multiple: false, expanded: false, choices: { 0 : 'STEP_ZERO', 1 : 'STEP_ONE',  2 : 'STEP_TWO', 3 : 'STEP_THREE', 4 : 'STEP_FOUR', 5 : 'NO_STEP' } } }
                    - { property: 'languages', type: 'easyadmin_autocomplete', type_options: { by_reference: false } }
                    - { property: 'userAgreement' }
            new:
               fields:
                    - { property: 'roles', type: 'choice', type_options: { required: true, multiple: true, expanded: true, choices: { 'ROLE_ADVISOR': 'ROLE_ADVISOR', 'ROLE_CONTRACTOR': 'ROLE_CONTRACTOR' }, data : { 'ROLE_CONTRACTOR': 'ROLE_CONTRACTOR' } } }
                    - { property: 'plainPassword', type: 'password' }
                    - { property: 'company', type: 'easyadmin_autocomplete', type_options: { by_reference: false } }

            disabled_actions:
                - 'delete'

        Language:
            class: ToolsBundle\Entity\Language
            label: 'Language'
            list:
                title: "Languages"
                fields:
                    - 'id'
                    - 'name'
