easy_admin:
    entities:
        User:
            class: UserBundle\Entity\User
            label: 'User'
            list:
                title: "Users"
                fields:
                    - 'id'
                    - 'firstname'
                    - 'lastname'
                    - 'username'
                    - 'email'
                    - 'roles'
            form:
                fields:
                    - { property: 'firstname', type: 'text' }
                    - { property: 'lastname', type: 'text' }
                    - { property: 'username', type: 'text' }
                    - { property: 'email', type: 'email' }
                    - { property: 'roles', type: 'choice', type_options: { required: true, multiple: true, expanded: true, choices: { 'ROLE_ADVISOR': 'ROLE_ADVISOR', 'ROLE_CONTRACTOR': 'ROLE_CONTRACTOR' } } }
