easy_admin:
    entities:

        WorkExp:
            class: MissionBundle\Entity\WorkExperience
            label: 'Work Experiences'
            list:
                title: "Work Experiences"
                fields:
                    - 'id'
                    - { property : 'name', trans : true, domaine : 'tools' }
                    - 'businessPractices'
                    - 'professionalExpertises'
                    - 'missionKinds'
                    - 'missionTitles'
            form:
                fields:
                    - { property: 'name', type: 'text' }
                    - { property: 'businessPractices', type: 'easyadmin_autocomplete', type_options: { by_reference: false } }
                    - { property: 'professionalExpertises', type: 'easyadmin_autocomplete', type_options: { by_reference: false } }
                    - { property: 'missionKinds', type: 'easyadmin_autocomplete', type_options: { by_reference: false } }
                    - { property: 'missionTitles', type: 'easyadmin_autocomplete', type_options: { by_reference: false } }

            disabled_actions:
                - 'delete'

        BusinessPra:
            class: 'MissionBundle\Entity\BusinessPractice'
            label: 'Business Practice'
            list:
                title: "Business Practice"
                fields:
                    - 'id'
                    - 'name'
                    - 'workExperiences'
        ProExp:
            class: 'MissionBundle\Entity\ProfessionalExpertise'
            label: 'Professional Expertise'
            list:
                title: "Professional Expertise"
                fields:
                    - 'id'
                    - 'name'
                    - 'workExperiences'
        MissionKind:
            class: 'MissionBundle\Entity\MissionKind'
            label: 'Mission Kind'
            list:
                title: "Mission Kind"
                fields:
                    - 'id'
                    - 'name'
                    - 'workExperiences'
        MissionTitle:
            class: 'MissionBundle\Entity\MissionTitle'
            label: 'Mission Title'
            list:
                title: "Mission Title"
                fields:
                    - 'id'
                    - 'category'
                    - 'title'
