<?php

namespace UserBundle\Repository;

/**
 * ElasticUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElasticUserRepository extends \Doctrine\ORM\EntityRepository
{
}
