<?php

namespace UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function checkEmailIsUnique($email)
    {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('count(u)')
            ->from('UserBundle:User', 'u')
            ->where('u.email = :email')
                ->setParameter('email', $email)
        ;

        return $qb->getQuery()->getSingleScalarResult();
    }
}
