# InboxBundle/Resources/config/routing.yml

show_all:
    path:   /
    defaults:
        _controller: InboxBundle:Inbox:showAllThread

show_thread:
    path:   /{id}
    defaults:
        _controller: InboxBundle:Inbox:showThread
