send_message_to_contractor:
    path:            /send_message_ctr
    defaults:
        _controller: InboxBundle:Action:sendMessageAdvisor
    methods: [POST]

send_message_to_advisor:
    path:            /send_message_adv
    defaults:
        _controller: InboxBundle:Action:sendMessageContractor
    methods:     [POST]
