calendar_booking:
    path:      /calendar
    defaults:
        _controller: CalendarBundle:Calendar:view
    options:
        expose: true

calendar_booking_get:
    path:      /calendar/get
    defaults:
        _controller: CalendarBundle:Calendar:getBooking
    options:
        expose: true

calendar_booking_add:
    path:      /calendar/add
    defaults:
        _controller: CalendarBundle:Calendar:addBooking
    options:
        expose: true

calendar_booking_remove:
    path:      /calendar/remove
    defaults:
        _controller: CalendarBundle:Calendar:removeBooking
    options:
        expose: true

calendar_booking_edit:
    path:      /calendar/edit
    defaults:
        _controller: CalendarBundle:Calendar:editBooking
    options:
        expose: true
