<?php

namespace BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{

    public function getCommentsByArticleIfAvailable($article)
    {
        $qb = $this->_em->createQueryBuilder();

        $qb->select('c')
            ->from('BlogBundle:Comment', 'c')
            ->where('c.article = :article')
            ->setParameter('article', $article)
            ->andWhere('c.status = 1')
            ;

        return $qb->getQuery()->getResult();
    }

}
