<?php

namespace BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NewsLettersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsLetterRepository extends EntityRepository
{

    public function getAvailableNewsLetters()
    {
        $qb = $this->_em->createQueryBuilder();

        $today = new \DateTime();

        $qb->select('n')
            ->from('BlogBundle:NewsLetter', 'n')
            ->where('n.publishedDate < :today')
            ->setParameter('today', $today)
            ->orderBy('n.publishedDate', 'ASC');

        return $qb->getQuery()->getResult();
    }
}
