# Mission Action

mission_view:
    path:      /mission/view/{missionId}
    defaults:
        _controller: MissionBundle:Mission:view

missions_all:
    path:      /missions
    defaults:
        _controller: MissionBundle:Mission:list

mission_interested:
    path:      /mission/interested/{missionId}
    defaults:
        _controller: MissionBundle:Mission:interested

mission_pitch:
    path:      /mission/pitch/{missionId}
    defaults:
        _controller: MissionBundle:Mission:pitch

mission_giveup:
    path:       /mission/giveup/{missionId}
    defaults:
        _controller: MissionBundle:Mission:giveUp

mission_users_selection:
    path:      /mission/selection/{missionId}
    defaults:
        _controller: MissionBundle:Mission:selection

mission_selection_takeback:
    path:      /mission/takeback/{missionId}
    defaults:
        _controller: MissionBundle:Mission:takeBack

# Mission Generator
mission_new_step_one:
    path:      /mission/new/1/{missionId}
    defaults:
        missionId:   null
        _controller: MissionBundle:MissionGenerator:stepOne

mission_new_step_two:
    path:      /mission/new/2/{missionId}
    defaults:
        _controller: MissionBundle:MissionGenerator:stepTwo

mission_new_step_three:
    path:      /mission/new/3/{missionId}
    defaults:
        _controller: MissionBundle:MissionGenerator:stepThree

mission_new_step_four:
    path:      /mission/new/4/{missionId}
    defaults:
        _controller: MissionBundle:MissionGenerator:stepFour

mission_new_step_five:
    path:      /mission/new/5/{missionId}
    defaults:
        _controller: MissionBundle:MissionGenerator:stepFive

mission_edit:
    path:      /mission/edit/{missionId}
    defaults:
        _controller: MissionBundle:MissionGenerator:editMission

mission_delete:
    path:      /mission/delete/{missionId}
    defaults:
        _controller: MissionBundle:MissionGenerator:delete

# certifications autocoomplete
certifications_autocomplete:
    path:            /certifications/autocomplete
    defaults:
        _controller: MissionBundle:Action:certificationsAutocomplete
        methode:     GET
