# Mission Action
mission_view:
    path:      /mission/view/{missionId}
    defaults:
        _controller: MissionBundle:Mission:view

mission_giveup:
    path:       /mission/giveup/{missionId}
    defaults:
        _controller: MissionBundle:Mission:giveUp

mission_interested:
    path:      /mission/interested/{missionId}
    defaults:
        _controller: MissionBundle:Mission:interested

mission_shortlist:
    path:      /mission/shortlist/{missionId}
    defaults:
        _controller: MissionBundle:Mission:shortlist

mission_answer_to_advisor:
    path:            /mission/answer/{userMissionId}
    defaults:
        _controller: MissionBundle:Mission:answerToAdvisor

# Action from Contractor on Advisor
user_mission_refuse:
    path:            /refuse/{userMissionId}
    defaults:
        _controller: MissionBundle:Mission:refuseUserMission

user_mission_add_to_contract:
    path:            /contract/add/{userMissionId}
    defaults:
        _controller: MissionBundle:Mission:addToContract

user_mission_add_to_shortlist:
    path:            /shortlist/add/{userMissionId}
    defaults:
        _controller: MissionBundle:Mission:addToShortlist

user_mission_remove_from_shortlist:
    path:            /shortlist/remove/{userMissionId}
    defaults:
        _controller: MissionBundle:Mission:removeFromShortlist

# Mission Generator
mission_new_step_one:
    path:      /mission/new/1/{missionId}
    defaults:
        missionId:   null
        _controller: MissionBundle:MissionGenerator:stepOne

mission_new_step_two:
    path:      /mission/new/2/{missionId}
    defaults:
        _controller: MissionBundle:MissionGenerator:stepTwo

mission_new_step_three:
    path:      /mission/new/3/{missionId}
    defaults:
        _controller: MissionBundle:MissionGenerator:stepThree

mission_new_step_four:
    path:      /mission/new/4/{missionId}
    defaults:
        _controller: MissionBundle:MissionGenerator:stepFour

mission_new_step_five:
    path:      /mission/new/5/{missionId}
    defaults:
        _controller: MissionBundle:MissionGenerator:stepFive

mission_edit:
    path:      /mission/edit/{missionId}
    defaults:
        _controller: MissionBundle:MissionGenerator:editMission

mission_delete:
    path:      /mission/delete/{missionId}
    defaults:
        _controller: MissionBundle:MissionGenerator:delete

# AJAX Request
certifications_autocomplete:
    path:            /certifications/autocomplete
    defaults:
        _controller: MissionBundle:Action:certificationsAutocomplete
    methods:     [GET]

user_mission_notes:
    path:            /save_notes
    defaults:
        _controller: MissionBundle:Action:saveNote
    methods:     [POST]

mission_count_match:
    path:            /mission/{missionId}/countMatch
    defaults:
        _controller: MissionBundle:Action:getNbMatch
