mission_new:
    path:      /mission/new
    defaults:
        _controller: MissionBundle:Mission:new

mission_view:
    path:      /mission/view/{missionId}
    defaults:
        _controller: MissionBundle:Mission:view

mission_edit:
    path:      /mission/edit/{id}
    defaults:
        _controller: MissionBundle:Mission:edit

missions_all:
    path:      /mission/all
    defaults:
        _controller: MissionBundle:Mission:list

mission_delete:
    path:      /mission/delete/{missionId}
    defaults:
        _controller: MissionBundle:Mission:delete

mission_pitch_all:
    path:       /mission/pitch/all
    defaults:
        _controller: MissionBundle:Mission:pitchAll

mission_pitch:
    path:      /mission/pitch/{missionId}
    defaults:
        _controller: MissionBundle:Mission:pitch

mission_teams_selection:
    path:      /mission/{missionId}/selection
    defaults:
        _controller: MissionBundle:Mission:selection

mission_selection_takeback:
    path:      /mission/{missionId}/selection/takeback
    defaults:
        _controller: MissionBundle:Mission:takeBack

mission_giveup:
    path:       /mission/giveup/{missionId}
    defaults:
        _controller: MissionBundle:Mission:giveUp
