mission_new:
    path:      /mission/new
    defaults:
        _controller: MissionBundle:Mission:new

mission_view_expert:
    path:      /mission/view/expert/{id}
    defaults:
        _controller: MissionBundle:Mission:view

mission_view_seeker:
    path:      /mission/view/seeker/{id}
    defaults:
        _controller: MissionBundle:Mission:view

mission_edit:
    path:      /mission/edit/{id}
    defaults:
        _controller: MissionBundle:Mission:edit

mission_step:
    path:      /mission/step/{id}
    defaults:
        _controller: MissionBundle:Mission:step

missions_all:
    path:      /mission/all
    defaults:
        _controller: MissionBundle:Mission:missionList

mission_pitch:
    path:      /mission/pitch/{id}
    defaults:
        _controller: MissionBundle:Mission:missionPitch
