mission_new:
    path:      /mission/new
    defaults:
        _controller: MissionBundle:Mission:new

mission_view:
    path:      /mission/view/{missionId}
    defaults:
        _controller: MissionBundle:Mission:view

mission_edit:
    path:      /mission/edit/{missionId}
    defaults:
        _controller: MissionBundle:Mission:edit

missions_all:
    path:      /missions
    defaults:
        _controller: MissionBundle:Mission:list

mission_delete:
    path:      /mission/delete/{missionId}
    defaults:
        _controller: MissionBundle:Mission:delete

mission_interested:
    path:      /mission/interested/{missionId}
    defaults:
        _controller: MissionBundle:Mission:interested

mission_pitch:
    path:      /mission/pitch/{missionId}
    defaults:
        _controller: MissionBundle:Mission:pitch

mission_giveup:
    path:       /mission/giveup/{missionId}
    defaults:
        _controller: MissionBundle:Mission:giveUp

mission_users_selection:
    path:      /mission/selection/{missionId}
    defaults:
        _controller: MissionBundle:Mission:selection

mission_selection_takeback:
    path:      /mission/takeback/{missionId}
    defaults:
        _controller: MissionBundle:Mission:takeBack
