mission_new:
    path:      /mission/new
    defaults:
        _controller: MissionBundle:Mission:new

mission_view_expert:
    path:      /mission/view/{id}
    defaults:
        _controller: MissionBundle:Mission:view

mission_view_seeker:
    path:      /mission/view/{id}
    defaults:
        _controller: MissionBundle:Mission:view

mission_edit:
    path:      /mission/edit/{id}
    defaults:
        _controller: MissionBundle:Mission:edit

mission_step:
    path:      /mission/step/{id}
    defaults:
        _controller: MissionBundle:Mission:step

missions_all:
    path:      /mission/all
    defaults:
        _controller: MissionBundle:Mission:missionList

mission_pitch:
    path:      /mission/pitch/{missionId}
    defaults:
        _controller: MissionBundle:Mission:missionPitch

mission_teams_selection:
    path:      /mission/{missionId}/selection
    defaults:
        _controller: MissionBundle:Mission:selection

mission_selection_takeback:
    path:      /mission/{missionId}/selection/takeback
    defaults:
        _controller: MissionBundle:Mission:takeBack
