user_profile_show:
    path:            /
    methods:         GET
    defaults:
        _controller: UserBundle:Profile:show

user_profile_edit:
    path:            /edit
    methods:         GET|POST
    defaults:
        _controller: UserBundle:Profile:edit
