fos_user_security_check:
    path:            /login_check
    methods:         POST
    defaults:
        _controller: 'FOSUserBundle:Security:check'

fos_user_security_login:
    path:            /login
    methods:         GET|POST
    defaults:
        _controller: 'UserBundle:Security:login'

fos_user_security_logout:
    path:            /logout
    methods:         GET
    defaults:
        _controller: 'FOSUserBundle:Security:logout'

