home_page_expert:
    path:      /
    defaults:
        _controller: HomePageBundle:Default:expert

home_page_seeker:
    path:      /contractor
    defaults:
        _controller: HomePageBundle:Default:seeker
