home_page_expert:
    path:      /
    defaults:
        _controller: HomePageBundle:Default:expert

home_page_seeker:
    path:      /contractor
    defaults:
        _controller: HomePageBundle:Default:seeker

home_page_terms:
    path: /terms
    defaults:
        _controller: HomePageBundle:Default:terms