home_page_advisor:
    path:      /
    defaults:
        _controller: HomePageBundle:Default:advisor

home_page_contractor:
    path:      /contractor
    defaults:
        _controller: HomePageBundle:Default:contractor

home_page_terms:
    path: /terms
    defaults:
        _controller: HomePageBundle:Default:terms

home_page_help:
    path: /help
    defaults:
        _controller: HomePageBundle:Default:help

home_page_about:
    path: /about
    defaults:
        _controller: HomePageBundle:Default:about

home_page_contact:
    path: /contact
    defaults:
        _controller: HomePageBundle:Default:contact
